### @TODO: Explain how to use this file

### Variables
@BASEURL =  http://localhost:8080
@DEFAULT_ACCOUNT_ID=1

### Health check
GET {{BASEURL}}/health

### Retrieve the account information
GET {{BASEURL}}/accounts/{{DEFAULT_ACCOUNT_ID}}


### Create an account
POST {{BASEURL}}/accounts
Content-Type: application/json
x-idempotency-key: {{$uuid}}

{
  "document_number": "12345678900"
}

### Create an account with invalid params
POST {{BASEURL}}/accounts
Content-Type: application/json
x-idempotency-key: {{$uuid}}

{
  "document_number": 123
}

### Create an account with empty body
POST {{BASEURL}}/accounts
Content-Type: application/json
x-idempotency-key: {{$uuid}}

{}

### Create a transaction
POST {{BASEURL}}/transactions
Content-Type: application/json
x-idempotency-key: {{$uuid}}

{
  "account_id": 1,
  "operation_type_id": 4,
  "amount": 123.45
}

### Create a transaction with empty body
POST {{BASEURL}}/transactions
Content-Type: application/json
x-idempotency-key: {{$uuid}}

{}

### Create a transaction with account_id 0
POST {{BASEURL}}/transactions
Content-Type: application/json
x-idempotency-key: {{$uuid}}

{
  "account_id": 0,
  "operation_type_id": 4,
  "amount": 123.45
}
